<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PC201808011230" name="Default test" tests="2" failures="1" timestamp="9 Dec 2019 09:39:18 GMT" time="4.031" errors="0">
  <testcase name="testFailed" time="2.013" classname="com.test.git.testNG.TimeOutTest">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method org.testng.internal.TestNGMethod.testFailed() didn&amp;apos;t finish within the time-out 2000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.testFailed() didn't finish within the time-out 2000
]]>
    </failure>
  </testcase> <!-- testFailed -->
  <testcase name="testSuccess" time="2.001" classname="com.test.git.testNG.TimeOutTest"/>
</testsuite> <!-- Default test -->
